### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by GGBond010219** [PandZz/Compiler#1]
学长您好，请问是否还有编译原理实验的文法解读等较基础问题的代码呢？我希望从中获取一些思路，感谢学长！
我的邮箱是2607098580@qq.com 
希望与您取得联系！

![微信截图_20241219012911](https://github.com/user-attachments/assets/92a564a6-d8ca-4b54-bccc-b60041fe2f75)

**Comment by PandZz** [comment]
这部分并没有多少难度，主要的难点就是使你的代码尽量覆盖多的语法组合以及一些平时不常用的语法，**例如**：

1. for 循环的 `([ForStmt] ';' [Cond] ';' [forStmt])`的三部分中，每一部分都可有可无，最终有 $2^3=8$ 种可能；
当然，关联性不大的部分不需要进行这样的排列组合，如：for 循环紧跟着的 `Stmt` 部分就不需要和上述8种可能进一步组合为16种可能，而只需要任意使其存在或不存在即可（或许还涉及到有无大括号的区别）

2. 数组作为形参时，需要指定其除第一维的大小，如：`func(int a[][2])`，当然你也可以指定第一维的大小（但实际的GCC编译器会忽略）

多关注课程网站和课程群，尽量独立完成
